version: "2"
linters:
  settings:
    tagalign:
      align: true
      strict: true
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/ilyakaznacheev/cleanenv
            - github.com/jmoiron/sqlx
            - github.com/ChronoFlow-Corp/spiry-backend-go/internal/config
            - github.com/ChronoFlow-Corp/spiry-backend-go/internal/transport/server
  default: all
  enable:
    - canonicalheader
