version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - whitespace

  disable-all: true

formatters:
  enable:
    - gci
    - gofmt
    - goimports
    - golines
    - swaggo

linter_settings:
  govet:
    check-shadowing: true
  staticcheck:
    checks: ["all"]
  errcheck:
    exclude-functions:
      - bytes.(*Reader).ReadAt
      - io.(*PipeReader).Read

run:
  timeout: 5m
  concurrency: 4
  modules-download-mode: readonly

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters: [gofmt]