services:
  spiry:
    build:
      target: spiry
    depends_on:
      database:
          condition: service_healthy
          restart: true
    env_file:
      - .env
    ports:
      - "1337:1337"
    volumes:
      - "${CONFIG_PATH_COMPOSE}:/app/config:ro"
      - "${JWT_CERTS_PATH_COMPOSE}:/app/jwt:ro"
      - "${SSL_CERTS_PATH_COMPOSE}:/app/certs:ro"
      - "${SSL_PRIVATE_PATH_COMPOSE}:/app/private:ro"
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s