CREATE TABLE IF NOT EXISTS tools (
    id uuid PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    model VARCHAR(255) NOT NULL,
    prompt TEXT NOT NULL,
    vars JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS chats ADD COLUMN tool_id uuid REFERENCES tools(id);
